# Development override for docker-compose
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=lab_journal_dev
      - JWT_SECRET=lab-journal-dev-secret-key
      - DEBUG=true
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001", "--reload", "--log-level", "debug"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - /app/build
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    stdin_open: true
    tty: true

  mongodb:
    environment:
      MONGO_INITDB_DATABASE: lab_journal_dev
    volumes:
      - mongodb_dev_data:/data/db

volumes:
  mongodb_dev_data:
  backend_node_modules:
  frontend_node_modules: